/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard API
 * Dashboard
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { AuthenticateModel } from '../models';
import { AuthenticateResultModel } from '../models';
import { ExternalAuthenticateModel } from '../models';
import { ExternalAuthenticateResultModel } from '../models';
import { ExternalLoginProviderInfoModel } from '../models';
/**
 * TokenAuthApi - axios parameter creator
 * @export
 */
export const TokenAuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {AuthenticateModel} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTokenAuthAuthenticatePost: async (body?: AuthenticateModel, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/TokenAuth/Authenticate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {ExternalAuthenticateModel} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTokenAuthExternalAuthenticatePost: async (body?: ExternalAuthenticateModel, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/TokenAuth/ExternalAuthenticate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTokenAuthGetExternalAuthenticationProvidersGet: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/TokenAuth/GetExternalAuthenticationProviders`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TokenAuthApi - functional programming interface
 * @export
 */
export const TokenAuthApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {AuthenticateModel} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiTokenAuthAuthenticatePost(body?: AuthenticateModel, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuthenticateResultModel>> {
            const localVarAxiosArgs = await TokenAuthApiAxiosParamCreator(configuration).apiTokenAuthAuthenticatePost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {ExternalAuthenticateModel} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiTokenAuthExternalAuthenticatePost(body?: ExternalAuthenticateModel, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ExternalAuthenticateResultModel>> {
            const localVarAxiosArgs = await TokenAuthApiAxiosParamCreator(configuration).apiTokenAuthExternalAuthenticatePost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiTokenAuthGetExternalAuthenticationProvidersGet(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ExternalLoginProviderInfoModel>>> {
            const localVarAxiosArgs = await TokenAuthApiAxiosParamCreator(configuration).apiTokenAuthGetExternalAuthenticationProvidersGet(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * TokenAuthApi - factory interface
 * @export
 */
export const TokenAuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {AuthenticateModel} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTokenAuthAuthenticatePost(body?: AuthenticateModel, options?: any): AxiosPromise<AuthenticateResultModel> {
            return TokenAuthApiFp(configuration).apiTokenAuthAuthenticatePost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ExternalAuthenticateModel} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTokenAuthExternalAuthenticatePost(body?: ExternalAuthenticateModel, options?: any): AxiosPromise<ExternalAuthenticateResultModel> {
            return TokenAuthApiFp(configuration).apiTokenAuthExternalAuthenticatePost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiTokenAuthGetExternalAuthenticationProvidersGet(options?: any): AxiosPromise<Array<ExternalLoginProviderInfoModel>> {
            return TokenAuthApiFp(configuration).apiTokenAuthGetExternalAuthenticationProvidersGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TokenAuthApi - object-oriented interface
 * @export
 * @class TokenAuthApi
 * @extends {BaseAPI}
 */
export class TokenAuthApi extends BaseAPI {
    /**
     * 
     * @param {AuthenticateModel} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TokenAuthApi
     */
    public apiTokenAuthAuthenticatePost(body?: AuthenticateModel, options?: any) {
        return TokenAuthApiFp(this.configuration).apiTokenAuthAuthenticatePost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {ExternalAuthenticateModel} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TokenAuthApi
     */
    public apiTokenAuthExternalAuthenticatePost(body?: ExternalAuthenticateModel, options?: any) {
        return TokenAuthApiFp(this.configuration).apiTokenAuthExternalAuthenticatePost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TokenAuthApi
     */
    public apiTokenAuthGetExternalAuthenticationProvidersGet(options?: any) {
        return TokenAuthApiFp(this.configuration).apiTokenAuthGetExternalAuthenticationProvidersGet(options).then((request) => request(this.axios, this.basePath));
    }
}
