/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard API
 * Dashboard
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ApplicationInfoDto
 */
export interface ApplicationInfoDto {
    /**
     * 
     * @type {string}
     * @memberof ApplicationInfoDto
     */
    version?: any;
    /**
     * 
     * @type {Date}
     * @memberof ApplicationInfoDto
     */
    releaseDate?: any;
    /**
     * 
     * @type {{ [key, string]: boolean;}}
     * @memberof ApplicationInfoDto
     */
    features?: any;
}
