/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard API
 * Dashboard
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AuthenticateModel
 */
export interface AuthenticateModel {
    /**
     * 
     * @type {string}
     * @memberof AuthenticateModel
     */
    userNameOrEmailAddress: any;
    /**
     * 
     * @type {string}
     * @memberof AuthenticateModel
     */
    password: any;
    /**
     * 
     * @type {boolean}
     * @memberof AuthenticateModel
     */
    rememberClient?: any;
}
