/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard API
 * Dashboard
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ChangeUserLanguageDto
 */
export interface ChangeUserLanguageDto {
    /**
     * 
     * @type {string}
     * @memberof ChangeUserLanguageDto
     */
    languageName: any;
}
