/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard API
 * Dashboard
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CreateRoleDto
 */
export interface CreateRoleDto {
    /**
     * 
     * @type {string}
     * @memberof CreateRoleDto
     */
    name: any;
    /**
     * 
     * @type {string}
     * @memberof CreateRoleDto
     */
    displayName: any;
    /**
     * 
     * @type {string}
     * @memberof CreateRoleDto
     */
    normalizedName?: any;
    /**
     * 
     * @type {string}
     * @memberof CreateRoleDto
     */
    description?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof CreateRoleDto
     */
    grantedPermissions?: any;
}
