/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard API
 * Dashboard
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CreateUserDto
 */
export interface CreateUserDto {
    /**
     * 
     * @type {string}
     * @memberof CreateUserDto
     */
    userName: any;
    /**
     * 
     * @type {string}
     * @memberof CreateUserDto
     */
    name: any;
    /**
     * 
     * @type {string}
     * @memberof CreateUserDto
     */
    surname: any;
    /**
     * 
     * @type {string}
     * @memberof CreateUserDto
     */
    emailAddress: any;
    /**
     * 
     * @type {boolean}
     * @memberof CreateUserDto
     */
    isActive?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof CreateUserDto
     */
    roleNames?: any;
    /**
     * 
     * @type {string}
     * @memberof CreateUserDto
     */
    password: any;
}
