/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard API
 * Dashboard
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ExternalAuthenticateModel
 */
export interface ExternalAuthenticateModel {
    /**
     * 
     * @type {string}
     * @memberof ExternalAuthenticateModel
     */
    authProvider: any;
    /**
     * 
     * @type {string}
     * @memberof ExternalAuthenticateModel
     */
    providerKey: any;
    /**
     * 
     * @type {string}
     * @memberof ExternalAuthenticateModel
     */
    providerAccessCode: any;
}
