/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard API
 * Dashboard
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ExternalLoginProviderInfoModel
 */
export interface ExternalLoginProviderInfoModel {
    /**
     * 
     * @type {string}
     * @memberof ExternalLoginProviderInfoModel
     */
    name?: any;
    /**
     * 
     * @type {string}
     * @memberof ExternalLoginProviderInfoModel
     */
    clientId?: any;
}
