/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard API
 * Dashboard
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GetRoleForEditOutput
 */
export interface GetRoleForEditOutput {
    /**
     * 
     * @type {RoleEditDto}
     * @memberof GetRoleForEditOutput
     */
    role?: any;
    /**
     * 
     * @type {Array&lt;FlatPermissionDto&gt;}
     * @memberof GetRoleForEditOutput
     */
    permissions?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof GetRoleForEditOutput
     */
    grantedPermissionNames?: any;
}
