/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard API
 * Dashboard
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PermissionDto
 */
export interface PermissionDto {
    /**
     * 
     * @type {number}
     * @memberof PermissionDto
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof PermissionDto
     */
    name?: any;
    /**
     * 
     * @type {string}
     * @memberof PermissionDto
     */
    displayName?: any;
    /**
     * 
     * @type {string}
     * @memberof PermissionDto
     */
    description?: any;
}
