/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard API
 * Dashboard
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface RegisterInput
 */
export interface RegisterInput {
    /**
     * 
     * @type {string}
     * @memberof RegisterInput
     */
    name: any;
    /**
     * 
     * @type {string}
     * @memberof RegisterInput
     */
    surname: any;
    /**
     * 
     * @type {string}
     * @memberof RegisterInput
     */
    userName: any;
    /**
     * 
     * @type {string}
     * @memberof RegisterInput
     */
    emailAddress: any;
    /**
     * 
     * @type {string}
     * @memberof RegisterInput
     */
    password: any;
    /**
     * 
     * @type {string}
     * @memberof RegisterInput
     */
    captchaResponse?: any;
}
