/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard API
 * Dashboard
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ResetPasswordDto
 */
export interface ResetPasswordDto {
    /**
     * 
     * @type {string}
     * @memberof ResetPasswordDto
     */
    adminPassword: any;
    /**
     * 
     * @type {number}
     * @memberof ResetPasswordDto
     */
    userId: any;
    /**
     * 
     * @type {string}
     * @memberof ResetPasswordDto
     */
    newPassword: any;
}
