/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard API
 * Dashboard
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface RoleEditDto
 */
export interface RoleEditDto {
    /**
     * 
     * @type {number}
     * @memberof RoleEditDto
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof RoleEditDto
     */
    name: any;
    /**
     * 
     * @type {string}
     * @memberof RoleEditDto
     */
    displayName: any;
    /**
     * 
     * @type {string}
     * @memberof RoleEditDto
     */
    description?: any;
    /**
     * 
     * @type {boolean}
     * @memberof RoleEditDto
     */
    isStatic?: any;
}
