/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard API
 * Dashboard
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface RoleListDto
 */
export interface RoleListDto {
    /**
     * 
     * @type {number}
     * @memberof RoleListDto
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof RoleListDto
     */
    name?: any;
    /**
     * 
     * @type {string}
     * @memberof RoleListDto
     */
    displayName?: any;
    /**
     * 
     * @type {boolean}
     * @memberof RoleListDto
     */
    isStatic?: any;
    /**
     * 
     * @type {boolean}
     * @memberof RoleListDto
     */
    isDefault?: any;
    /**
     * 
     * @type {Date}
     * @memberof RoleListDto
     */
    creationTime?: any;
}
