/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard API
 * Dashboard
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TenantDto
 */
export interface TenantDto {
    /**
     * 
     * @type {number}
     * @memberof TenantDto
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof TenantDto
     */
    tenancyName: any;
    /**
     * 
     * @type {string}
     * @memberof TenantDto
     */
    name: any;
    /**
     * 
     * @type {boolean}
     * @memberof TenantDto
     */
    isActive?: any;
}
