/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard API
 * Dashboard
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UserLoginInfoDto
 */
export interface UserLoginInfoDto {
    /**
     * 
     * @type {number}
     * @memberof UserLoginInfoDto
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof UserLoginInfoDto
     */
    name?: any;
    /**
     * 
     * @type {string}
     * @memberof UserLoginInfoDto
     */
    surname?: any;
    /**
     * 
     * @type {string}
     * @memberof UserLoginInfoDto
     */
    userName?: any;
    /**
     * 
     * @type {string}
     * @memberof UserLoginInfoDto
     */
    emailAddress?: any;
}
